create extension if not exists pgcrypto;

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  sku text not null unique,
  price numeric(12, 2) not null check (price >= 0),
  old_price numeric(12, 2) check (old_price is null or old_price >= price),
  stock integer not null default 0 check (stock >= 0),
  status text not null default 'draft' check (status in ('active', 'draft')),
  unit text not null,
  badge text,
  image_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.customers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  full_name text not null,
  phone text,
  location text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create sequence public.order_number_seq start 1049;

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  customer_id uuid not null references public.customers(id),
  total numeric(12, 2) not null default 0 check (total >= 0),
  payment_status text not null default 'pending'
    check (payment_status in ('pending', 'paid', 'refunded')),
  delivery_status text not null default 'unfulfilled'
    check (delivery_status in ('unfulfilled', 'packing', 'ready', 'delivered', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  product_name text not null,
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  line_total numeric(12, 2) generated always as (unit_price * quantity) stored
);

create table public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  created_at timestamptz not null default now()
);

create table public.discounts (
  id bigint generated by default as identity primary key,
  code text not null unique,
  percent_off integer check (percent_off between 1 and 100),
  active boolean not null default true,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  category text not null,
  excerpt text,
  image_url text not null,
  status text not null default 'draft' check (status in ('published', 'draft')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger categories_set_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create trigger customers_set_updated_at
before update on public.customers
for each row execute function public.set_updated_at();

create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

create trigger discounts_set_updated_at
before update on public.discounts
for each row execute function public.set_updated_at();

create trigger articles_set_updated_at
before update on public.articles
for each row execute function public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

create or replace function public.create_storefront_order(
  p_customer_name text,
  p_customer_email text,
  p_customer_phone text,
  p_items jsonb
)
returns table (
  order_id uuid,
  order_number text,
  total numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer_id uuid;
  v_order_id uuid;
  v_order_number text;
  v_total numeric(12, 2) := 0;
  v_item jsonb;
  v_product public.products%rowtype;
  v_product_id bigint;
  v_quantity integer;
begin
  if length(trim(coalesce(p_customer_name, ''))) < 2 then
    raise exception 'Invalid customer name';
  end if;

  if length(trim(coalesce(p_customer_email, ''))) < 3 then
    raise exception 'Invalid customer email';
  end if;

  if jsonb_typeof(p_items) <> 'array' then
    raise exception 'Items must be an array';
  end if;

  if jsonb_array_length(p_items) < 1 or jsonb_array_length(p_items) > 50 then
    raise exception 'Invalid item count';
  end if;

  insert into public.customers (email, full_name, phone)
  values (
    lower(trim(p_customer_email)),
    trim(p_customer_name),
    nullif(trim(coalesce(p_customer_phone, '')), '')
  )
  on conflict (email) do update
  set
    full_name = excluded.full_name,
    phone = coalesce(excluded.phone, public.customers.phone)
  returning id into v_customer_id;

  v_order_number := '#LY' || lpad(nextval('public.order_number_seq')::text, 4, '0');

  insert into public.orders (order_number, customer_id)
  values (v_order_number, v_customer_id)
  returning id into v_order_id;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    if coalesce(v_item ->> 'productId', '') !~ '^[0-9]+$'
      or coalesce(v_item ->> 'quantity', '') !~ '^[0-9]+$' then
      raise exception 'Invalid order item';
    end if;

    v_product_id := (v_item ->> 'productId')::bigint;
    v_quantity := (v_item ->> 'quantity')::integer;

    if v_quantity < 1 or v_quantity > 99 then
      raise exception 'Invalid quantity';
    end if;

    select *
    into v_product
    from public.products
    where id = v_product_id and status = 'active'
    for update;

    if not found then
      raise exception 'Product is unavailable';
    end if;

    if v_product.stock < v_quantity then
      raise exception 'Insufficient inventory';
    end if;

    update public.products
    set stock = stock - v_quantity
    where id = v_product.id;

    insert into public.order_items (order_id, product_id, product_name, unit_price, quantity)
    values (v_order_id, v_product.id, v_product.name, v_product.price, v_quantity);

    v_total := v_total + (v_product.price * v_quantity);
  end loop;

  update public.orders
  set total = v_total
  where id = v_order_id;

  return query
  select o.id, o.order_number, o.total
  from public.orders o
  where o.id = v_order_id;
end;
$$;

revoke all on function public.create_storefront_order(text, text, text, jsonb) from public;
grant execute on function public.create_storefront_order(text, text, text, jsonb) to service_role;

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.admin_users enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.discounts enable row level security;
alter table public.articles enable row level security;

create policy categories_public_read
on public.categories for select
to anon, authenticated
using (active or public.is_admin());

create policy categories_admin_all
on public.categories for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy products_public_read
on public.products for select
to anon, authenticated
using (status = 'active' or public.is_admin());

create policy products_admin_all
on public.products for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy admin_users_read_self
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

create policy customers_admin_all
on public.customers for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy orders_admin_all
on public.orders for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy order_items_admin_all
on public.order_items for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy discounts_public_read
on public.discounts for select
to anon, authenticated
using (active or public.is_admin());

create policy discounts_admin_all
on public.discounts for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy articles_public_read
on public.articles for select
to anon, authenticated
using (status = 'published' or public.is_admin());

create policy articles_admin_all
on public.articles for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;

create policy product_images_public_read
on storage.objects for select
to anon, authenticated
using (bucket_id = 'product-images');

create policy product_images_admin_insert
on storage.objects for insert
to authenticated
with check (bucket_id = 'product-images' and public.is_admin());

create policy product_images_admin_update
on storage.objects for update
to authenticated
using (bucket_id = 'product-images' and public.is_admin())
with check (bucket_id = 'product-images' and public.is_admin());

create policy product_images_admin_delete
on storage.objects for delete
to authenticated
using (bucket_id = 'product-images' and public.is_admin());

insert into public.categories (name, slug, image_url)
values
  ('Bread & Bakery', 'bread-bakery', 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=700&q=85'),
  ('Flour & Baking', 'flour-baking', 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=700&q=85'),
  ('Fruits & Vegetables', 'fruits-vegetables', 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=700&q=85'),
  ('Fresh Meals & Pizzas', 'fresh-meals-pizzas', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=85'),
  ('Beverages', 'beverages', 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=700&q=85'),
  ('Fresh Meat', 'fresh-meat', 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?auto=format&fit=crop&w=700&q=85'),
  ('Dairy & Eggs', 'dairy-eggs', 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=700&q=85'),
  ('Sauces & Marinades', 'sauces-marinades', 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?auto=format&fit=crop&w=700&q=85')
on conflict (slug) do nothing;

insert into public.products (id, name, category, sku, price, old_price, stock, status, unit, badge, image_url)
values
  (1, 'Artisan Sourdough Loaf', 'Bread & Bakery', 'BRD-1001', 6.50, 8.00, 42, 'active', '500g', 'Sale', 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=700&q=90'),
  (2, 'Organic Hass Avocados', 'Fruits & Vegetables', 'FRT-1024', 5.90, null, 68, 'active', 'Pack of 3', 'Organic', 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=700&q=90'),
  (3, 'Sweet Garden Strawberries', 'Fruits & Vegetables', 'FRT-1018', 4.75, null, 16, 'active', '250g', 'Fresh', 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=700&q=90'),
  (4, 'Farm Fresh Whole Milk', 'Dairy & Eggs', 'DRY-1006', 3.25, null, 34, 'active', '1 litre', 'Local', 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=700&q=90'),
  (5, 'Sun-Kissed Navel Oranges', 'Fruits & Vegetables', 'FRT-1029', 4.20, null, 0, 'draft', '1kg', 'Popular', 'https://images.unsplash.com/photo-1547514701-42782101795e?auto=format&fit=crop&w=700&q=90'),
  (6, 'Free Range Brown Eggs', 'Dairy & Eggs', 'DRY-1011', 5.50, null, 21, 'active', '12 eggs', null, 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&w=700&q=90'),
  (7, 'Fresh Rigatoni Pasta', 'Fresh Meals & Pizzas', 'MEA-1015', 4.90, null, 11, 'active', '400g', null, 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=700&q=90'),
  (8, 'Atlantic Salmon Fillet', 'Fresh Meat', 'MEA-1021', 14.50, null, 8, 'active', '350g', 'Premium', 'https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?auto=format&fit=crop&w=700&q=90')
on conflict (sku) do nothing;

select setval(
  pg_get_serial_sequence('public.products', 'id'),
  (select max(id) from public.products),
  true
);

insert into public.discounts (code, percent_off, ends_at)
values
  ('FRESH20', 20, '2026-06-30T23:59:59Z'),
  ('WELCOME10', 10, null)
on conflict (code) do nothing;

insert into public.articles (title, slug, category, image_url, status, published_at)
values
  ('A simpler way to plan your weekly groceries', 'simpler-weekly-groceries', 'Kitchen tips', 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=85', 'published', '2026-06-01T09:00:00Z'),
  ('Three bright salads for warmer days', 'three-bright-salads', 'Recipes', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85', 'published', '2026-05-29T09:00:00Z'),
  ('Meet the growers behind our organic greens', 'organic-greens-growers', 'Local stories', 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=900&q=85', 'published', '2026-05-28T09:00:00Z')
on conflict (slug) do nothing;
