CREATE TABLE IF NOT EXISTS public.order_events (
  id bigint generated by default as identity primary key,
  order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  actor text NOT NULL DEFAULT 'system',
  event_type text NOT NULL,
  message text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_order_events_order_id
  ON public.order_events(order_id, created_at);

ALTER TABLE public.order_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_all_order_events" ON public.order_events;
CREATE POLICY "service_role_all_order_events"
  ON public.order_events FOR ALL TO service_role
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "customers_read_own_order_events" ON public.order_events;
CREATE POLICY "customers_read_own_order_events"
  ON public.order_events FOR SELECT TO authenticated
  USING (
    order_id IN (
      SELECT o.id FROM public.orders o
      JOIN public.customers c ON c.id = o.customer_id
      WHERE lower(c.email) = lower(auth.jwt() ->> 'email')
    )
  );
