create table public.categories (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.categories(id) on delete set null,
  name text not null unique,
  slug text not null unique,
  description text,
  image_url text,
  active boolean not null default true,
  show_on_home boolean not null default false,
  include_in_menu boolean not null default false,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger categories_set_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

alter table public.categories enable row level security;

create policy categories_public_read
on public.categories for select
to anon, authenticated
using (active or public.is_admin());

create policy categories_admin_all
on public.categories for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into public.categories (name, slug, image_url, active, show_on_home, include_in_menu, display_order)
values
  ('Pantry', 'pantry', null, true, false, true, 10),
  ('Produce', 'produce', null, true, false, true, 20),
  ('Bakery', 'bakery', null, true, false, true, 30),
  ('Dairy & Eggs', 'dairy-eggs', 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=700&q=85', true, true, true, 40),
  ('Fresh Meals & Pizzas', 'fresh-meals-pizzas', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=85', true, true, false, 50),
  ('Fresh Meat', 'fresh-meat', 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?auto=format&fit=crop&w=700&q=85', true, true, false, 60);

insert into public.categories (parent_id, name, slug, image_url, active, show_on_home, include_in_menu, display_order)
select id, 'Pasta & Noodles', 'pasta-noodles', null, true, false, false, 11 from public.categories where name = 'Pantry'
union all select id, 'Grains & Beans', 'grains-beans', null, true, false, false, 12 from public.categories where name = 'Pantry'
union all select id, 'Snacks', 'snacks', null, true, false, false, 13 from public.categories where name = 'Pantry'
union all select id, 'Oil, Vinegar & Spices', 'oil-vinegar-spices', null, true, false, false, 14 from public.categories where name = 'Pantry'
union all select id, 'Sauces & Marinades', 'sauces-marinades', 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?auto=format&fit=crop&w=700&q=85', true, true, false, 15 from public.categories where name = 'Pantry'
union all select id, 'Dressings', 'dressings', null, true, false, false, 16 from public.categories where name = 'Pantry'
union all select id, 'Fruits & Vegetables', 'fruits-vegetables', 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=700&q=85', true, true, false, 21 from public.categories where name = 'Produce'
union all select id, 'Vegetables', 'vegetables', null, true, false, false, 22 from public.categories where name = 'Produce'
union all select id, 'Fruit', 'fruit', null, true, false, false, 23 from public.categories where name = 'Produce'
union all select id, 'Herbs & Aromatics', 'herbs-aromatics', null, true, false, false, 24 from public.categories where name = 'Produce'
union all select id, 'Drinks', 'drinks', null, true, false, true, 25 from public.categories where name = 'Produce'
union all select id, 'Bread & Bakery', 'bread-bakery', 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=700&q=85', true, true, false, 31 from public.categories where name = 'Bakery'
union all select id, 'Flour & Baking', 'flour-baking', 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=700&q=85', true, true, false, 32 from public.categories where name = 'Bakery'
union all select id, 'Bread', 'bread', null, true, false, false, 33 from public.categories where name = 'Bakery'
union all select id, 'Buns & Rolls', 'buns-rolls', null, true, false, false, 34 from public.categories where name = 'Bakery'
union all select id, 'Bagels & Breakfast', 'bagels-breakfast', null, true, false, false, 35 from public.categories where name = 'Bakery'
union all select id, 'Gluten-Free', 'gluten-free', null, true, false, false, 36 from public.categories where name = 'Bakery'
union all select id, 'Milk & Cream', 'milk-cream', null, true, false, false, 41 from public.categories where name = 'Dairy & Eggs'
union all select id, 'Eggs & Butter', 'eggs-butter', null, true, false, false, 42 from public.categories where name = 'Dairy & Eggs'
union all select id, 'Cheese', 'cheese', null, true, false, false, 43 from public.categories where name = 'Dairy & Eggs'
union all select id, 'Yogurt & Cultured Dairy', 'yogurt-cultured-dairy', null, true, false, false, 44 from public.categories where name = 'Dairy & Eggs'
union all select id, 'Plant-Based', 'plant-based', null, true, false, false, 45 from public.categories where name = 'Dairy & Eggs';

insert into public.categories (parent_id, name, slug, image_url, active, show_on_home, include_in_menu, display_order)
select id, 'Beverages', 'beverages', 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=700&q=85', true, true, false, 26 from public.categories where name = 'Drinks'
union all select id, 'Coffee', 'coffee', null, true, false, false, 27 from public.categories where name = 'Drinks'
union all select id, 'Tea & Elixirs', 'tea-elixirs', null, true, false, false, 28 from public.categories where name = 'Drinks'
union all select id, 'Juices', 'juices', null, true, false, false, 29 from public.categories where name = 'Drinks';

insert into public.categories (name, slug, active, display_order)
select distinct
  p.category,
  regexp_replace(lower(p.category), '[^a-z0-9]+', '-', 'g') || '-' || substr(md5(p.category), 1, 6),
  true,
  1000
from public.products p
where not exists (
  select 1 from public.categories c where c.name = p.category
);

alter table public.products
add constraint products_category_fkey
foreign key (category)
references public.categories(name)
on update cascade
on delete restrict;
